### ISSUE TITLE
[BUG] Unable to paste text in the follow-up prompt

### ISSUE THREAD

**Issue by ZenfadeCOM** [devgpt-labs/devgpt-releases#44] opened 2023-09-09 21:05 UTC
Unable to paste text in the follow-up prompt.
![image](https://github.com/february-labs/devgpt-releases/assets/3357754/c06c1c3b-c327-4843-bd97-83357d27c385)

**Comment by vastolf** [comment] 2023-09-11 15:15
I'm experiencing this as well on MacOS using an M1 Mac and 1.0.9

It appears that it doesn't allow pasting multiple lines when using this "single line" input. This really inhibits responding to prompts after my initial question, such as when it asked me "can you paste the error you're receiving?" 

Maybe it's due to what I'm trying to paste being too long -- but if this is this case I'd rather it let me paste and then show the character count being over 150, maybe red to indicate that it's too much.

**Comment by ash-lewis** [comment] 2023-09-14 10:28
I can confirm this is a live bug for me as well, we'll work on getting this resolved in the next version. Thanks for reporting!

**Closed** 2023-09-22 20:20 UTC
Labels: Bug, Compatability
